#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
sed -i '/errorfile 504/a listen antinvestor' /etc/haproxy/haproxy.cfg
sed -i '/listen antinvestor/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 27944-web-01 3.236.56.179:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 27944-web-01 3.236.56.179:80 check/a         server 27944-web-02 3.239.57.79:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
